env:
  browser: false
  commonjs: true
  es6: true
  jasmine: true
  jest: true
ext: '.js'
extends:
  - 'plugin:jasmine/recommended'
  - 'eslint:recommended'
  - 'airbnb'
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: false
plugins:
  - jasmine
rules:
  camelcase: 0
  'arrow-body-style': 0
  'react/no-multi-comp': 0
  'react/require-extension': 0
  'class-methods-use-this': 0
  'no-underscore-dangle': 0
  'consistent-return': 0
  'no-multi-spaces': 0
  'import/newline-after-import': 0
  'prefer-template': 0
  'strict': 0
  'prefer-rest-params': 0
  'no-console': 0
  'func-names': 1
  'no-plusplus': 0
  'no-param-reassign': 0
  'no-restricted-syntax': 0
  'no-prototype-builtins': 0
  'global-require': 0
  'padded-blocks': 0
  'no-trailing-spaces': 0
  'eqeqeq': 0
  'key-spacing': 0
  'no-continue': 0
